{"uuid":"0efcb044-8715-40b4-afd5-325c4f618004","historyId":"857a30d9a9d202d43c0130e1288bd5fc","fullName":"com.qa.api.gorest.tests.UpdateUserTest.updateUser_createAndThenDeleteAPITest","labels":[{"name":"package","value":"com.qa.api.gorest.tests.UpdateUserTest"},{"name":"testClass","value":"com.qa.api.gorest.tests.UpdateUserTest"},{"name":"testMethod","value":"updateUser_createAndThenDeleteAPITest"},{"name":"parentSuite","value":"Rest API Test Suite"},{"name":"suite","value":"Rest API regression Test"},{"name":"subSuite","value":"com.qa.api.gorest.tests.UpdateUserTest"},{"name":"host","value":"DESKTOP-MUPOVES"},{"name":"thread","value":"1728@DESKTOP-MUPOVES.TestNG-test=Rest API regression Test-3(19)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"updateUser_createAndThenDeleteAPITest","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [Siddhi384165NEW] but found [Siddhi384165NEWFAIL]","trace":"java.lang.AssertionError: expected [Siddhi384165NEW] but found [Siddhi384165NEWFAIL]\r\n\tat org.testng.Assert.fail(Assert.java:99)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1037)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)\r\n\tat org.testng.Assert.assertEquals(Assert.java:122)\r\n\tat org.testng.Assert.assertEquals(Assert.java:629)\r\n\tat org.testng.Assert.assertEquals(Assert.java:639)\r\n\tat com.qa.api.gorest.tests.UpdateUserTest.updateUser_createAndThenDeleteAPITest(UpdateUserTest.java:94)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\n"},"stage":"finished","steps":[],"attachments":[{"name":"updateUser_createAndThenDeleteAPITest failed and screenshot taken!","source":"c423ede3-63f4-4b4e-b21b-53311dd6d6f2-attachment","type":"text/plain"}],"parameters":[],"start":1641989121541,"stop":1641989130454}